/* eslint-disable @nx/enforce-module-boundaries */
import RecoilProvider from '@/providers/RecoilProvider';
import '@/styles/global.css';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>
        <RecoilProvider>
          <div>{children}</div>
        </RecoilProvider>
      </body>
    </html>
  );
}
