/* eslint-disable @nx/enforce-module-boundaries */
import '@/styles/global.css';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>
        <div className="m-8">{children}</div>
      </body>
    </html>
  );
}
